name: Patch

on:
  schedule:
  - cron: "0 20 * * *"
  push:
    branches:
      - 'main'

jobs:
  patch:
    name: "Patch YouTube with ReVanced"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '19'

    - name: "Check YouTube version"
      run: |
        bash check_yt_version.sh

    - name: Run patch.sh
      run: |
        bash patch.sh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update latest YouTube version
        file_pattern: yt-version

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: revanced_youtube*.apk

