name: Patch

on:
  schedule:
  - cron: "0 20 * * *"

jobs:
  patch:
    name: "Patch YouTube with ReVanced"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run patch.sh
      run: |
        bash patch.sh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update latest YouTube version
        file_pattern: yt-version